### ISSUE TITLE
Execution problems with a modified simple.cpp

### ISSUE THREAD

**Issue by Jrwilliams43** [Twinklebear/osp-mpi-distrib-samples#1]
Hello, 

I am working a program to draw a lot spheres. I have used your code as base. I have problems when running the code on more than two nodes. Sometimes when running on 4 nodes there is a signal 11 error during ospShutdown and on 16 nodes processes tend to get stuck in ospCommit(model). I would appreciated you would  take a look. 

[simple.txt](https://github.com/Twinklebear/osp-mpi-distrib-samples/files/2576972/simple.txt)

Regards,
Jerrold

**Comment by Jrwilliams43** [comment]
Here is the modified code 

#include < vector >
#include < cmath >
#include < cassert >
#include < iostream >
#include < cstring >
#include < fstream>
#include < random >
#include < string >
#include < array >
#include < cstdio >
#include < mpi.h >
#include < ospray/ospray.h >
#include < ospray/ospcommon/vec.h >
#include "../header/cTimer.h"
using namespace ospcommon;

double gen_start,gen_end,model_start,model_end,render_start,render_end;
double elapsed_gen,elapsed_model,elapsed_render;
double max_elapsed_gen,max_elapsed_model,max_elapsed_render;
#define NUM_ATOMS 794 // 4294967295 
struct Particle {
	vec3f pos;
	int color_id;

	Particle(float x, float y, float z)
		: pos(vec3f{x, y, z}), color_id(0)
		{}
};

void write_ppm(const std::string &file_name, const int width, const int height,
		const uint32_t *img);

int main(int argc, char **argv) {
	int provided = 0;
	MPI_Init_thread(&argc, &argv, MPI_THREAD_MULTIPLE, &provided);
	/*if(provided == MPI_THREAD_MULTIPLE){
		std::cout<<"MPI_MULTI_THREAD SUPPORT"<<std::endl;
	}
	else{
		std::cout<<"NOT SUPPORTED"<<std::endl;
	}*/
	int world_size, rank;
	MPI_Comm_size(MPI_COMM_WORLD, &world_size);
	MPI_Comm_rank(MPI_COMM_WORLD, &rank);
	{
                  char host_name[1024] = {0};
                  gethostname(host_name, 1023);
                  std::cout << "global_rank " << rank << " on host "<< host_name<<std::endl; 

        }

	if (ospLoadModule("mpi") != OSP_NO_ERROR) {
		throw std::runtime_error("Failed to load OSPRay MPI module");
	}

	OSPDevice device = ospNewDevice("mpi_distributed");
	ospDeviceSet1i(device, "masterRank", 0);
//	ospDeviceSet1i(device, "numThreads",32);
	//ospDeviceSet1i(device, "setAffinity",0);
	//ospDeviceSet1i(device, "logLevel",2);
	//ospDeviceSetString(device,"logOutput","cout");
	ospDeviceSetStatusFunc(device, [](const char *msg) { std::cout << msg << "\n"; });
	ospDeviceCommit(device);
	ospSetCurrentDevice(device);

	//if (rank == 0) {
	//	std::cout<<"Provided: "<<provided<<std::endl;
	//}
	MPI_Barrier(MPI_COMM_WORLD);	
 	int numCols = world_size/2;
	const vec3f cam_pos(((float)-NUM_ATOMS/2.0f)+(((float)numCols/2.0f)*(float)NUM_ATOMS) ,((float)NUM_ATOMS/2.0f), 9);//9

	const vec3f cam_up(0, 1, 0);
	const vec3f cam_at(((float)-NUM_ATOMS/2.0f)+(((float)numCols/2.0f)*    (float)NUM_ATOMS) ,0, 0);
	const vec3f cam_dir = cam_at - cam_pos;

	std::random_device rd;
	std::mt19937 rng(rd());
	std::vector<float> atoms;
	std::vector<float> colors;
	
	MPI_Barrier(MPI_COMM_WORLD);
	gen_start = MPI_Wtime();

	int offsetX = (rank%numCols * (NUM_ATOMS)) ;
 	int offsetY = rank>=numCols? NUM_ATOMS: 0;
	for(int i = -(NUM_ATOMS/2)+offsetX; i < (NUM_ATOMS/2)+offsetX; i++){
	//std::cout<<i<<std::endl;
		for(int j = -(NUM_ATOMS/2)+offsetY; j < (NUM_ATOMS/2)+offsetY; j++){
			for(int k = -(NUM_ATOMS/2); k <(NUM_ATOMS/2); k++){
				atoms.push_back((float)i);
                		atoms.push_back((float)j);
                		atoms.push_back((float)k);
				atoms.push_back(1.0f);
                		colors.push_back(static_cast<float>(rank) / world_size);
                		colors.push_back(static_cast<float>(rank) / world_size);
                		colors.push_back(static_cast<float>(rank) / world_size);
				colors.push_back(1.0);
			}
		}
	}

//	MPI_Barrier(MPI_COMM_WORLD);
	gen_end = MPI_Wtime();
	elapsed_gen = gen_end - gen_start;

		

	

	// Make the OSPData which will refer to our particle and color data.
	// The OSP_DATA_SHARED_BUFFER flag tells OSPRay not to share our buffer,
	// instead of taking a copy.
	size_t atomsSize = atoms.size()/4;
	size_t colorsSize = colors.size()/4;
	OSPData sphere_data = ospNewData(atomsSize, OSP_FLOAT3A,
		atoms.data());
	ospCommit(sphere_data);
	OSPData color_data = ospNewData(colorsSize, OSP_FLOAT4,
		colors.data());
	ospCommit(color_data);

	// Create the sphere geometry that we'll use to represent our particles
	OSPGeometry spheres = ospNewGeometry("spheres");
	ospSetData(spheres, "spheres", sphere_data);
	ospSetData(spheres, "color", color_data);
	ospSet1f(spheres, "radius", 0.25f);
	ospCommit(spheres);

	// Create the model we'll place all our scene geometry into, representing
	// the world to be rendered. If we don't need sort-last compositing to be
	// performed (i.e. all our objects are opaque), we don't need to specify
	// any regions to the model.
	OSPModel model = ospNewModel();
	ospAddGeometry(model, spheres);
	
	MPI_Barrier(MPI_COMM_WORLD);//this line and the line below are for TIMING if they are commented uncomment the line above ospCommit(model);
	model_start = MPI_Wtime();	

	//MPI_Barrier(MPI_COMM_WORLD);
	ospCommit(model);

	//MPI_Barrier(MPI_COMM_WORLD);
	model_end = MPI_Wtime();//this line and the line below are used for TIMING
	elapsed_model = model_end - model_start;
	//std::cout<<"After Model "<<rank<<std::endl;
	// Setup the camera we'll render the scene from
	//const osp::vec2i img_size{1920, 1080};
	//const osp::vec2i img_size{(1920*6), (1080*3)};//Everest
	const osp::vec2i img_size{3840, 2160};//4k
	//const osp::vec2i img_size{1920, 1080};//1080p
	OSPCamera camera = ospNewCamera("orthographic");
	//OSPCamera camera = ospNewCamera("perspective");
	//ospSet1f(camera,"height", world_size*NUM_ATOMS);

	ospSet1f(camera,"height", world_size>2?(float)(numCols*NUM_ATOMS*0.60f):2.0f*(float)NUM_ATOMS);
	ospSet1f(camera, "aspect",(float)img_size.x/(float)img_size.y);
	ospSet3fv(camera, "pos", &cam_pos.x);
	ospSet3fv(camera, "up", &cam_up.x);
	ospSet3fv(camera, "dir", &cam_dir.x);

	ospCommit(camera);
	//OSPCamera camera = ospNewCamera("orthographic");
	// For distributed rendering we must use the MPI raycaster
	OSPRenderer renderer = ospNewRenderer("mpi_raycast");
	// Setup the parameters for the renderer
	
	ospSet1i(renderer, "spp", 1);
	ospSet1f(renderer, "bgColor", 1.f);
	ospSetObject(renderer, "model", model);
	ospSetObject(renderer, "camera", camera);
	ospCommit(renderer);
//std::cout<<"After renderer "<<rank<<std::endl;
	// Create a framebuffer to render the image too
	OSPFrameBuffer framebuffer = ospNewFrameBuffer(img_size, OSP_FB_RGBA8, OSP_FB_COLOR);
	ospFrameBufferClear(framebuffer, OSP_FB_COLOR);
//std::cout<<"After ospNewFrameBuffer "<<rank<<std::endl;
//	cTimer rendererTimer;
//	rendererTimer.reset();
	MPI_Barrier(MPI_COMM_WORLD);//this line and the line below are for TIMING if this line is commented out uncomment the line above ospRenderFrame
	render_start = MPI_Wtime();	

	//MPI_Barrier(MPI_COMM_WORLD);
	ospRenderFrame(framebuffer, renderer, OSP_FB_COLOR);

	//MPI_Barrier(MPI_COMM_WORLD);
	render_end = MPI_Wtime();// this line and the line below are for TIMING
	elapsed_render = render_end - render_start;
	//double min_gen_start,min_model_start,min_render_start;
	//double max_gen_end,max_model_end,max_render_end;

	//MPI_Reduce(&gen_start,&min_gen_start,1,MPI_DOUBLE,MPI_MIN,0,MPI_COMM_WORLD);
//	MPI_Reduce(&model_start,&min_model_start,1,MPI_DOUBLE,MPI_MIN,0,MPI_COMM_WORLD);
//	MPI_Reduce(&render_start,&min_render_start,1,MPI_DOUBLE,MPI_MIN,0,MPI_COMM_WORLD);
//	The following three lines are for TIMING if not TIMING comment these lines.
	MPI_Reduce(&elapsed_gen,&max_elapsed_gen,1,MPI_DOUBLE,MPI_MAX,0,MPI_COMM_WORLD);
	MPI_Reduce(&elapsed_model,&max_elapsed_model,1,MPI_DOUBLE,MPI_MAX,0,MPI_COMM_WORLD);
	MPI_Reduce(&elapsed_render,&max_elapsed_render,1,MPI_DOUBLE,MPI_MAX,0,MPI_COMM_WORLD);

//	double myTime = rendererTimer.getElapsedMilliseconds();
//	std::cout<<"My Rank: "<<rank<<" My Time: "<<myTime<<std::endl;
	//}
	if (rank == 0) {
		const uint32_t *img = static_cast<const uint32_t*>(ospMapFrameBuffer(framebuffer, OSP_FB_COLOR));
		write_ppm("/ccs/home/jrwilliams/limit_particles"+std::to_string(world_size)+".ppm",img_size.x,img_size.y,img);
		std::cout << "Image saved to 'limit_particles.ppm'\n";
		ospUnmapFrameBuffer(img, framebuffer);
		//This lines are for TIMING. if not Timing comment this lines out.
		std::cout<<"Particle Pos generation time: "<<max_elapsed_gen<<"s"<<std::endl;
		std::cout<<"Model Commit time: "<<max_elapsed_model<<"s"<<std::endl;
		std::cout<<"Rendering time: "<<max_elapsed_render<<"s"<<std::endl;
	}

	// Clean up all our objects
	MPI_Barrier(MPI_COMM_WORLD);
	ospRelease(framebuffer);
	ospRelease(renderer);
	ospRelease(camera);
	ospRelease(model);
	ospRelease(spheres);
	ospShutdown();

	MPI_Finalize();

	return 0;
}

void write_ppm(const std::string &file_name, const int width, const int height,
		const uint32_t *img)
{
	FILE *file = fopen(file_name.c_str(), "wb");
	if (!file) {
		throw std::runtime_error("Failed to open file for PPM output");
	}

	fprintf(file, "P6\n%i %i\n255\n", width, height);
	std::vector<uint8_t> out(3 * width, 0);
	for (int y = 0; y < height; ++y) {
		const uint8_t *in = reinterpret_cast<const uint8_t*>(&img[(height - 1 - y) * width]);
		for (int x = 0; x < width; ++x) {
			out[3 * x] = in[4 * x];
			out[3 * x + 1] = in[4 * x + 1];
			out[3 * x + 2] = in[4 * x + 2];
		}
		fwrite(out.data(), out.size(), sizeof(uint8_t), file);
	}
	fprintf(file, "\n");
	fclose(file);
}

**Comment by Twinklebear** [comment]
Hey @Jrwilliams43 , thanks for reporting this issue! Unfortunately I've gotten a bit behind on updating this code so it may not work on the devel version (upcoming 1.8) of OSPRay. Which version are you trying to run with? I'll update these examples for the upcoming 1.8 release (OSPRay's current devel branch) since it changes a bit how the API works (for the better) and improves performance a lot.

Also for formatting code on github you can put it inside the [backticks](https://guides.github.com/features/mastering-markdown/)

**Comment by Jrwilliams43** [comment]
I am using ospray1.7.0. Sorry about the formatting.

**Comment by Jrwilliams43** [comment]
I realize now that the issue is with the OSPray I compiled. Thank you for the reply

**Comment by Twinklebear** [comment]
No problem, there will also be problems with this repo when you're running on 1.8 though it should be ok on 1.7. I'll work on updating this repo to the devel of OSPRay to provide a sample.
